name: Release pipeline

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/c13n-io/c13n-go-testenv:latest
      options: -v ${{ github.workspace }}:/c13n
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install dev dependencies
        run: cd /c13n && make dev-deps

      - name: Install zip
        run: apk add --no-cache --update zip

      - name: Create release assets
        run: cd /c13n && make release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ steps.tagName.outputs.tag }}
          files: |
            /c13n/c13n-build/*

